plugins {
    id 'java-library'
}

description = 'support'

dependencies {
    // Domain
    implementation project(':domain')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework.boot:spring-boot-starter-json'

    // api/batch 양쪽에서 CacheConfig, @Cacheable 등을 그대로 사용할 수 있도록 api로 노출
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    api 'org.springframework.boot:spring-boot-starter-cache'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Spring AI
    implementation platform('org.springframework.ai:spring-ai-bom:1.1.8')
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // HTML Parser
    implementation 'org.jsoup:jsoup:1.21.1'
}
