plugins {
    id 'org.springframework.boot'
}

description = 'batch'

dependencies {
    // Domain
    implementation project(':domain')

    // Spring Batch
    implementation 'org.springframework.boot:spring-boot-starter-batch'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // dotenv
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
