plugins {
    id 'org.springframework.boot'
}

description = 'api'

dependencies {
    // Domain
    implementation project(':domain')

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.springframework.kafka:spring-kafka-test'

    // WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Spring AI
    implementation platform('org.springframework.ai:spring-ai-bom:1.1.8')
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
